image: python:3.11

stages:
  - build
  - test
  - deploy

default:
  tags:
    - us-west-2


#####
# Build
#####

before_script:
  - source env/bin/activate

build:
  stage: build
  before_script:
    - echo "Stops attempt to activate env before env is built..."
  script:
    - pip install virtualenv
    - virtualenv env
    - source env/bin/activate
    - pip install poetry
    - poetry install --with dev
  artifacts:
    expire_in: 1 hour
    paths:
      - env

#####
# Tests: Safety, Formatting, Tests
#####

safety:
  stage: test
  script:
    - poe safety

lint:
  stage: test
  script:
    - poe lint

test:
  stage: test
  script:
    - poe tests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    expire_in: 1 hour
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

#####
# Deploy: Packaging
#####

pages:
  stage: deploy
  when: manual
  script:
    - poe docs
  artifacts:
    paths:
    - public
    

release:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - poetry build
  artifacts:
    paths:
      - dist/
